name = "personal-website"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[site]
bucket = "./build"

[env.production]
name = "personal-website-prod"

[[routes]]
pattern = "ttdddan.com"
custom_domain = true

[[routes]]
pattern = "www.ttdddan.com"
custom_domain = true

[env.staging]
name = "personal-website-staging"
